### ISSUE TITLE
[S2 - PBI8] Membuat halaman pilihan poli

### ISSUE THREAD

**Issue by divanilutfiah** [SI-RPL-2022/SI4301_SIKESMAS#11]
User Stories : Sebagai pasien, saya ingin memilih poli yang ingin saya tuju untuk kebutuhan pemeriksaan kesehatan saya.
Navigasi : Setelah melakukan login dan mengakses halaman home, maka terdapat pilihan poli yang ingin dituju untuk selanjutnya melakukan booking antrean.
![image](https://user-images.githubusercontent.com/92225961/168074368-3f080b4f-397f-432d-9d43-b4a178677590.png)

**Comment by tienfkusumasari** [comment]
done

**Comment by tienfkusumasari** [comment]
issue dilengkapi ya

**Comment by abdulazis99** [comment]
![WhatsApp Image 2022-06-09 at 13 16 39](https://user-images.githubusercontent.com/92225961/172787558-ed21b485-9f1b-40a1-9000-5a77879967ee.jpeg)
