### ISSUE TITLE
[S2 - PBI11] Menginputkan hasil periksa dan tindakan

### ISSUE THREAD

**Issue by divanilutfiah** [SI-RPL-2022/SI4301_SIKESMAS#14]
User Stories : Dokter Menginputkan hasil periksa dan tindakan sehingga Hasil periksa dan tindakan akan terupdate dari data dokter

Navigasi: Dokter melakukan login dan masuk ke halaman utama dokter, lalu Dokter melakukan input hasil periksa dan tindakan dari pasien

![image](https://user-images.githubusercontent.com/73094272/168087360-22d9f416-435c-48bb-8aaf-f9753aaa227c.png)

![image](https://user-images.githubusercontent.com/73094272/168087415-f51c3618-176a-445d-bfc4-3fff139f7ebf.png)

![image](https://user-images.githubusercontent.com/73094272/171580820-304da2da-f3cf-4e12-a9ca-d59918b1c8bf.png)

**Comment by tienfkusumasari** [comment]
done dari tampilan sampai logic tinggal do lengkapi alur di PBI (tandai yang dibuat)
