### ISSUE TITLE
[S2 - PBI12] Melihat hasil periksa dari dokter

### ISSUE THREAD

**Issue by divanilutfiah** [SI-RPL-2022/SI4301_SIKESMAS#15]
User Stories: Sebagai pasien, saya ingin melihat hasil periksa saya yang telah dilakukan pemeriksaan oleh dokter.

Navigasi: Pasien melakukan login dan masuk ke halaman pasien, lalu pasien masuk ke menu Hasil Periksa dan pasien melihat hasil pemeriksaan dari dokter.
![image](https://user-images.githubusercontent.com/101638509/171590537-da4f9c85-37f6-4cd2-b006-599cec47ffc5.png)
![image](https://user-images.githubusercontent.com/101638509/171590047-264cb742-7488-43bb-bda9-d32e842c7e18.png)
![image](https://user-images.githubusercontent.com/101638509/171590327-c7579a72-79ec-4564-a380-4e9786ec4de3.png)

**Comment by tienfkusumasari** [comment]
done tampilan dan logic hanya issue kurang lengkap

**Comment by tienfkusumasari** [comment]
done lengkap
