### ISSUE TITLE
[S2 - PB13] Melakukan checkout resep

### ISSUE THREAD

**Issue by divanilutfiah** [SI-RPL-2022/SI4301_SIKESMAS#16]
User Stories : Sebagai pasien yang telah melihat hasil periksa yang menunjukkan untuk bisa dilakukan rawat jalan, maka saya ingin melakukan checkout resep agar bisa menebus obat yang telah diresepkan oleh dokter.

**Comment by tienfkusumasari** [comment]
done dr sisi aplikasi tp di isseu kurang lengkap dan kondisi2 konstrain belum dilengkapi

**Comment by abdulazis99** [comment]
Flow chart
![WhatsApp Image 2022-06-09 at 13 16 39](https://user-images.githubusercontent.com/92225961/172787788-7b116d9d-5df9-4dc4-b13d-9af030a97ce3.jpeg)
