### ISSUE TITLE
[S2 - PBI14] Melakukan booking kamar

### ISSUE THREAD

**Issue by divanilutfiah** [SI-RPL-2022/SI4301_SIKESMAS#17]
User Stories : Pasien melakukan booking kamar ketika hasil periksa dari dokter mengarahkan tindakan rawat inap, setelah klik button booking kamar rawat inap maka pasien akan diarahkan pada tampilan pilihan kamar rawat inap kemudian diarahkan pada proses booking rawat inap di rumah sakit.

**Comment by tienfkusumasari** [comment]
done, fitur enhance utk jumlah stok kamar yang availabel aja yang muncul
