### ISSUE TITLE
[S3 - PBI15] Membuat halaman update data booking kamar

### ISSUE THREAD

**Issue by jilankanza** [SI-RPL-2022/SI4301_SIKESMAS#18]
User Stories : Sebagai admin, saya akan melakukan update data booking kamar yang nantinya akan dipesan oleh pasien.

Navigasi : Admin melakukan login, dan masuk ke halaman login. Lalu, admin memilih halaman daftar kamar dan admin melakukan edit data pada booking kamar.
![image](https://user-images.githubusercontent.com/101638509/173893295-b68decc4-1ea4-46f7-9eee-5f15016066e8.png)
![image](https://user-images.githubusercontent.com/101638509/173893439-d1fce2dc-11fd-4828-ae59-4bbbe6d33e49.png)
![image](https://user-images.githubusercontent.com/101638509/173893489-c08cc8be-7d32-4c90-8572-2163814f01f8.png)
![image](https://user-images.githubusercontent.com/101638509/173893758-a81da1e2-ce19-4d73-873a-17a0017e88ad.png)

**Comment by abdulazis99** [comment]
![image](https://user-images.githubusercontent.com/92225961/173730173-bcfffdf2-00aa-4680-bf85-23a146a708f1.png)
User stories : Sebagai admin, saya akan melakukan acc booking kamar yang telah dilakukan oleh pasien.
Navigasi : login sebagai admin lalu masuk ke layanan dan update ruang rawat inap untuk melakukan perubahan

**Comment by tienfkusumasari** [comment]
done (S3) perbaiki konsep logika design sistem nya
