### ISSUE TITLE
[S3 - PBI17] Menambahkan jadwal dokter yang sedang praktik

### ISSUE THREAD

**Issue by jilankanza** [SI-RPL-2022/SI4301_SIKESMAS#19]
User Story: Sebagai super admin, saya ingin menambahkan jadwal dokter sehingga pasien dapat melihat jadwal dokter yang sedang praktik
Navigasi: Login sebagai superadmin , lalu ke tambah dokter pada halaman utama. setelah dibuat, super admin akan ke halaman daftar dokter untuk melihat jadwal dokter dan pasien dapat melihat jadwal dokter pada halaman jadwal dokter.
![image](https://user-images.githubusercontent.com/73094272/175080987-d99fdf1d-ac7c-4ab3-a566-29feab49f3e4.png)
![image](https://user-images.githubusercontent.com/73094272/175880512-59d864d0-c494-4fdc-82ff-da34974dd625.png)

**Comment by abdulazis99** [comment]
![image](https://user-images.githubusercontent.com/92225961/173735193-42be2af8-c710-454b-a7f3-89cf03ff1b72.png)
User stories : Sebagai admin, saya ingin membuat halaman jadwal dokter yang sedang praktik pada sistem puskesmas.
Navigasi : Login sebagai admin lalu masuk kedalam layanan pada bagian dokter dan melakukan perubahan jadwal dokter oleh admin

**Comment by tienfkusumasari** [comment]
done (SP3)
