### ISSUE TITLE
[SI - PBI4] Membuat halaman profil pasien

### ISSUE THREAD

**Issue by abdulazis99** [SI-RPL-2022/SI4301_SIKESMAS#2]
Sebagai pasien, saya ingin melihat data diri saya di halaman profil untuk memastikan apakah sesuai.

**Comment by abdulazis99** [comment]
![image](https://user-images.githubusercontent.com/92225961/163722004-ee41755a-5110-4b2d-b407-ff4808c5cc5f.png)
Profile pasien

**Comment by Timoteusliseka** [comment]
Menambahkan database pada SIKESMAS

**Comment by tienfkusumasari** [comment]
ada bug dikit dari foto pas edit

**Comment by abdulazis99** [comment]
Menambahkan navigasi menuju profile pasien "in progress"
