### ISSUE TITLE
[SI - PBI16] Melihat live nomor antrian periksa

### ISSUE THREAD

**Issue by divanilutfiah** [SI-RPL-2022/SI4301_SIKESMAS#26]

**Comment by abdulazis99** [comment]
![image](https://user-images.githubusercontent.com/92225961/173734652-149a0ce6-4559-4174-b165-dd7471e3ed02.png)
User stories : Sebagai pasien, saya ingin melihat nomor antrian periksa yang sedang ditangani.
Navigasi : Pertama tama login sebagai pasien lalu scrol di bagian index dan akan ada tampilan live count dari nomor antrian yang ada saat ini.

**Comment by tienfkusumasari** [comment]
perbaiki cara menuliskan isu , coding udah sesuai (SP3)
