### ISSUE TITLE
[SI - PBI19] Melihat riwayat periksa

### ISSUE THREAD

**Issue by divanilutfiah** [SI-RPL-2022/SI4301_SIKESMAS#28]

**Comment by abdulazis99** [comment]
![image](https://user-images.githubusercontent.com/92225961/173736704-6a5dad69-c19b-4ea0-af76-a1b4ba752c74.png)
User stories : Sebagai pasien, saya ingin melihat riwayat periksa pada puskesmas melalui sistem sikesmas.
Navigasi : ....

**Comment by tienfkusumasari** [comment]
cdoing selesai tp issue tidak sesuai standar
