### ISSUE TITLE
[SI - PBI20] Melakukan report data periksa

### ISSUE THREAD

**Issue by divanilutfiah** [SI-RPL-2022/SI4301_SIKESMAS#29]
User stories : Sebagai admin, report data pasien yang datang ke puskesmas akan masuk dalam sistem database pasien kemudian akan masuk pada halaman report yang ada pada role admin untuk melihat grafik data pasien di puskesmas.
Navigasi : Admin melakukan login pada website, kemudian pada halaman admin akan terdapat menu data puskesmas yang akan menampilkan data grafik pasien dan review dari pasien.
![image](https://user-images.githubusercontent.com/63994047/175856925-ffec7693-f7e1-40e9-b014-f80e1bf99bb7.png)

**Comment by abdulazis99** [comment]
![image](https://user-images.githubusercontent.com/92225961/173737407-e65ebc30-88e7-4efc-9d76-d8b48dcb034d.png)
User stories : Sebagai admin, saya akan membuat laporan periksa dari setiap pasien, sehingga dapat dilakukan pengarsipan dengan baik melalui sistem.
Navigasi : Login sebagai admin, lalu masuk kedalam layanan dan masuk ke rawat inap dan disana bisa dilakukan update availability ruang rawat inap saat ini.

**Comment by tienfkusumasari** [comment]
done (S3)
