### ISSUE TITLE
[SI - PBI7] Membuat halaman tambah admin

### ISSUE THREAD

**Issue by divanilutfiah** [SI-RPL-2022/SI4301_SIKESMAS#4]

**Comment by divanilutfiah** [comment]
![Halaman Tambah Admin 1 - Sprint1](https://user-images.githubusercontent.com/63994047/163722307-37575621-7f36-4a58-94fb-13c3d8388bd8.jpg)
![Halaman Tambah Admin 2 - Sprint1](https://user-images.githubusercontent.com/63994047/163722308-6841df67-995e-4283-8a63-59a5a6f3b7fb.jpg)
![Halaman Tambah Admin 3 - Sprint1](https://user-images.githubusercontent.com/63994047/163722309-8f81b9d0-fb62-4719-802c-97bcb38b05cc.jpg)
![Halaman Tambah Admin 4 - Sprint1](https://user-images.githubusercontent.com/63994047/163722311-685efb7c-028e-4925-aa5a-ae87c4cde58f.jpg)
![Halaman Tambah Admin 5 - Sprint1](https://user-images.githubusercontent.com/63994047/163722297-880c2861-ffdd-4431-92a8-2fbb327deba8.jpg)
![Halaman Tambah Admin 6 - Sprint1](https://user-images.githubusercontent.com/63994047/163722302-006ade4f-9aad-464f-ae2a-e25ae1208f72.jpg)
Halaman Tambah Admin

**Comment by abdulazis99** [comment]
menambahkan route admin
